import { createComputerUseServer } from '@zavora-ai/computer-use-mcp';
import { connectInProcess } from '@zavora-ai/computer-use-mcp/client';
import fs from 'fs';
const c = await connectInProcess(createComputerUseServer());
const w = await c.callTool('list_windows', { bundle_id: 'chrome.exe' });
const m = w.content.map(p=>p.text||'').join('\n').match(/\{[\s\S]*\}/);
const j = JSON.parse(m[0]); const win = j.windows[0];
// click with prepare_display (hides non-target apps before acting)
const cl = await c.callTool('left_click', { coordinate: [win.bounds.x + 855, win.bounds.y + 269], target_window_id: win.windowId, focus_strategy: 'prepare_display' });
console.log('click:', cl.content.map(p=>p.text||'').join(' ').slice(0,200));
await new Promise(r=>setTimeout(r,800));
const ty = await c.callTool('type', { text: 'focustest2', target_window_id: win.windowId, focus_strategy: 'prepare_display' });
console.log('type:', ty.content.map(p=>p.text||'').join(' ').slice(0,200));
await new Promise(r=>setTimeout(r,800));
const f = await c.callTool('get_frontmost_app', {});
console.log('frontmost:', f.content.map(p=>p.text||'').join(' ').slice(0,120));
const shot = await c.screenshot({ target_window_id: win.windowId });
const img = shot.content.find(p => p.type === 'image');
fs.writeFileSync('_focus2.jpg', Buffer.from(img.data, 'base64'));
console.log('saved');
await c.close();
